apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  source:
    git:
      url: https://github.com/dbuchko/tanzu-java-web-app
      ref:
        branch: main